domain="ivytime.gay"
bind_address="127.0.0.1"
port=8029
site_repo="https://github.com/uberfig/ivytime.gay.git"
branch="main"
real_ip_header="CF-Connecting-IP"

pg_user="ivy"
pg_password="password"
pg_host="127.0.0.1"
pg_port=5432
pg_dbname="ivyhost"
