CREATE TABLE visitors (
	uid 				BIGSERIAL NOT NULL PRIMARY KEY UNIQUE,
	ip_address_hash		VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE paths (
	pid 			BIGSERIAL NOT NULL PRIMARY KEY UNIQUE,
	path			TEXT NOT NULL UNIQUE,
	unique_visitors	BIGINT NOT NULL DEFAULT 0,
	total_requests	BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE requests (
	uid			BIGINT NOT NULL REFERENCES visitors(uid) ON DELETE CASCADE,
	pid			BIGINT NOT NULL REFERENCES paths(pid) ON DELETE CASCADE,
	created_at	BIGINT NOT NULL
);
